name: guardiano_advmobprog_longexam1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_screenutil: ^5.9.3
  http: ^1.6.0
  shared_preferences: ^2.5.5
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/.env

  fonts:
    - family: Klavika
      fonts:
        - asset: assets/fonts/KlavikaBoldBold.otf
    - family: Frutiger
      fonts:
        - asset: assets/fonts/FrutigerLTStd-Roman.otf
  uses-material-design: true
